version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postal_postgres
    environment:
      POSTGRES_DB: postal
      POSTGRES_USER: postal
      POSTGRES_PASSWORD: postal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: postal_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
